name = "wav-fortran"
version = "0.1.0"
license = "MIT"
author = "Murase Hijiri"
maintainer = "murase.hijiri.arch@gmail.com"
copyright = "Copyright 2024, Murase Hijiri"
description = "Read and Write WAV Files Using Modern Fortran"
homepage = "https://github.com/Murase-Hijiri/wav-fortran"
categories = ["io", "audio"]
keywords = ["wav"]

[library]
source-dir = "src"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

